SELECT 
a.DT_MOVIMENTO_ESTOQUE,
a.NR_DOCUMENTO,
a.CD_MATERIAL,
OBTER_DESC_MATERIAL(A.CD_MATERIAL) DS_MATERIAL,
a.QT_MOVIMENTO,
A.NR_ATENDIMENTO,
OBTER_DADOS_ATENDIMENTO(A.NR_ATENDIMENTO,'NP') NM_PACIENTE,
(SELECT DISTINCT
NR_INTERNO_CONTA
FROM MATERIAL_ATEND_PACIENTE
WHERE NR_ATENDIMENTO = A.NR_ATENDIMENTO
AND CD_MATERIAL = A.CD_MATERIAL
AND CD_SETOR_ATENDIMENTO = A.CD_SETOR_ATENDIMENTO
AND DT_CONTA = A.DT_MOVIMENTO_ESTOQUE) NR_INTERNO_CONTA,
substr(obter_descricao_padrao('OPERACAO_ESTOQUE','DS_OPERACAO',
A.CD_OPERACAO_ESTOQUE),1,80) ds_acao,
obter_Saldo_Disp_estoque(a.cd_estabelecimento, a.cd_material, a.cd_local_estoque,a.dt_mesano_referencia) qt_disponivel
FROM MOVIMENTO_ESTOQUE_V a
WHERE  a.DT_MOVIMENTO_ESTOQUE BETWEEN :dt_inicial AND fim_dia(:dt_final)
AND (a.NR_DOCUMENTO  = :nr_documento OR :nr_documento = 0)
AND (a.cd_material = :cd_material or :cd_material = 0)
AND A.NR_ATENDIMENTO IS NOT NULL
@SQL_WHERE      
ORDER BY a.DT_MOVIMENTO_ESTOQUE DESC, a.NR_DOCUMENTO DESC



SELECT 
a.DT_MOVIMENTO_ESTOQUE,
a.NR_DOCUMENTO,
a.CD_MATERIAL,
OBTER_DESC_MATERIAL(A.CD_MATERIAL) DS_MATERIAL,
a.QT_MOVIMENTO, 
OBTER_DADOS_ATENDIMENTO(A.NR_ATENDIMENTO,'NP') NM_PACIENTE,
substr(obter_descricao_padrao('OPERACAO_ESTOQUE','DS_OPERACAO',
A.CD_OPERACAO_ESTOQUE),1,80) ds_acao,
obter_Saldo_Disp_estoque(a.cd_estabelecimento, a.cd_material, a.cd_local_estoque,a.dt_mesano_referencia) qt_disponivel
FROM MOVIMENTO_ESTOQUE_V a
WHERE  a.DT_MOVIMENTO_ESTOQUE BETWEEN :dt_inicial AND fim_dia(:dt_final)
AND (a.NR_DOCUMENTO  = :nr_documento OR :nr_documento = 0)
AND (a.cd_material = :cd_material or :cd_material = 0)
AND A.NR_ATENDIMENTO IS NOT NULL
@SQL_WHERE      
ORDER BY a.DT_MOVIMENTO_ESTOQUE DESC, a.NR_DOCUMENTO DESC


SELECT DISTINCT
CD_LOCAL_ESTOQUE CD,
DS_LOCAL_ESTOQUE DS
FROM LOCAL_ESTOQUE